---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-template-backend
  title: Quarkus Backend Application
  description: creates the quarkus -workshop
  tags:
    - java
    - quarkus
    - maven
    - workshop
spec:
  owner: mad-workshop-authors
  type: service
  parameters:
    - title: Provide information about the new component
      required:
        - cluster_id
        - namespace
        - owner
      properties:
        cluster_id:
          title: Cluster Id
          type: string
          description: Id of the cluster
          default: .apps.cluster-xxxxx.xxxxx.sandboxXXXX.opentlc.com
        namespace:
          title: Namespace
          type: string
          description: Namespace
          default: devhub2
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - User
    - title: Provide information about the CI method
      required:
        - ci
      properties:
        ci:
          title: Select a CI method
          type: string
          description: This action will create a CI pipeline for your application based on
            chosen method
          default:  ../../custom-templates/helm/cicd/
          enum:
            -  ../../custom-templates/helm/cicd/
          enumNames:
            - Tekton
      dependencies:
        ci:
          oneOf:
            - properties:
                ci:
                  const: ../../custom-templates/helm/cicd/
            - required:
                - imageRepository
                - namespace
              properties:
                ci:
                  const:  ../../custom-templates/helm/cicd/
                imageRepository:
                  title: Select a registry
                  type: string
                  default: Internal OpenShift Registry
                  enum:
                    - quay.io
                    - image-registry.openshift-image-registry.svc:5000
                  enumNames:
                    - Quay
                    - Internal OpenShift Registry
  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          githubOrg: ${{parameters.githubOrg}}
          repoName: ${{parameters.namespace}}-backend
          owner: ${{parameters.owner}}
          cluster_id: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          component_id: ${{parameters.namespace}}-poi-backend-app
    - id: publishSource
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        sourcePath: ./source
        allowedHosts:
          - github.com
        description: ${{parameters.description}}
        repoUrl: github.com?owner=${{parameters.githubOrg}}&repo=${{parameters.namespace}}-backend
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: registerSource
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /catalog-info.yaml
    - id: templateGitops
      name: Generating the deployment resources and artefacts
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{parameters.namespace}}-poi-backend-app
          description: ${{parameters.description}}
          destination: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-backend-gitops
          source_repository: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-backend
          repository_name: ${{parameters.namespace}}-backend
          git_owner: ${{parameters.githubOrg}}
          cluster: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          image_host: ${{parameters.image_host}}
          image_name: ${{parameters.namespace}}/poi-backend-app
          image_tag: ${{parameters.image_tag}}
        targetPath: ./tenant-gitops
    - id: publishGitops
      name: Publishing to Deployment Resource Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=${{parameters.githubOrg}}&repo=${{parameters.namespace}}-backend-gitops
        title: gitops resources for ${{parameters.namespace}}-poi-backend-app
        description: gitops resources for ${{parameters.namespace}}-poi-backend-app
        sourcePath: ./tenant-gitops
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: createArgoResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{parameters.namespace}}-poi-backend-app-bootstrap
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-backend-gitops.git
        path: argocd/
  output:
    links:
      - title: Source Code Repository
        url: ${{steps.publishSource.output.remoteUrl}}
      - title: Pipeline status
        url: https://console-openshift-console${{parameters.cluster_id}}/dev-pipelines/ns/${{parameters.namespace}}/
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{steps.registerSource.output.entityRef}}
